export enum Alignment {
  LeftTackle,
  LeftGuard,
  Center,
  RightGuard,
  RightTackle,
  XReceiver,
  YReceiver,
  ZReceiver,
  AReceiver,
  BReceiver,
  CReceiver,
  QBUnderCenter,
  QBShotgun,
  FullBackI,
  FullBackOffset,
  HalfBack,
  HBLeftShotgun,
  HBRightShotgun,

  RightDefensiveEnd,
  RightDefensiveTackle,
  NoseTackle,
  LeftDefensiveTackle,
  LeftDefensiveEnd,
  StrongOutsideLinebacker,
  WeakOutsideLinebacker,
  MiddleLinebacker,
  StrongMiddleLinebacker,
  WeakMiddleLinebacker,
  XCornerback,
  YCornerback,
  Nickleback,
  Dimeback,
  StrongSafety,
  WeakSafety,
  CenterfieldSafety,

  FGHolder,
  FGKicker,

  Punter,
  PuntLeftWallBlocker,
  PuntCenterWallBlocker,
  PuntRightWallBlocker,

  PuntBlocker1,
  PuntBlocker2,
  PuntBlocker3,
  PuntBlocker4,
  PuntBlocker5,
  PuntBlocker6,
  PuntBlocker7,
  PuntBlocker8,
  PuntBlocker9,
  PuntBlocker10,
  PuntReturner,

  KickoffKicker,
  KickoffStreaker1,
  KickoffStreaker2,
  KickoffStreaker3,
  KickoffStreaker4,
  KickoffStreaker5,
  KickoffStreaker6,
  KickoffStreaker7,
  KickoffStreaker8,
  KickoffStreaker9,
  KickoffStreaker10,

  KickoffBlocker1,
  KickoffBlocker2,
  KickoffBlocker3,
  KickoffBlocker4,
  KickoffBlocker5,
  KickoffBlocker6,
  KickoffBlocker7,
  KickoffBlocker8,
  KickoffBlocker9,
  KickoffBlocker10,
  KickoffReturner,

  OffenseCaptain,
  DefenseCaptain,
}
